engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,lib,module"
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,lib,module"
    exclude_fingerprints:
    # Excludes 'The variable $site_data is not named in camelCase.'
    # modules/custom/cu_inventory/cu_inventory_stats/cu_inventory_stats.inc Line 23
    - 793e02706ebf47a81718e392be7af9b0

ratings:
  paths:
  - "modules/custom/"
  - "modules/features/"
exclude_paths:
- "**.scss"
- "libraries/"
- "tests/"
- "modules/contrib/"
